insert into customer (id, first_name, last_name, email, job, mobile) values (1, 'Veda', 'Berriball', 'vberriball0@mlb.com', 'Dental Hygienist', '399 422 1295');
insert into customer (id, first_name, last_name, email, job, mobile) values (2, 'Alasdair', 'Rhodus', 'arhodus1@blogger.com', 'Analog Circuit Design manager', '130 941 7748');
insert into customer (id, first_name, last_name, email, job, mobile) values (3, 'Marlon', 'Garahan', 'mgarahan2@cdc.gov', 'Tax Accountant', '691 338 2367');
insert into customer (id, first_name, last_name, email, job, mobile) values (4, 'Norton', 'Quainton', 'nquainton3@nba.com', 'Marketing Assistant', '102 246 7621');
insert into customer (id, first_name, last_name, email, job, mobile) values (5, 'Ogdon', 'Ackery', 'oackery4@about.me', 'Quality Engineer', '291 762 7606');
insert into customer (id, first_name, last_name, email, job, mobile) values (6, 'Paul', 'Goncaves', 'pgoncaves5@prweb.com', 'Design Engineer', '236 326 4424');
insert into customer (id, first_name, last_name, email, job, mobile) values (7, 'Cello', 'Olorenshaw', 'colorenshaw6@tripod.com', 'Accountant I', '356 358 5648');
insert into customer (id, first_name, last_name, email, job, mobile) values (8, 'Sibbie', 'Curl', 'scurl7@friendfeed.com', 'Environmental Tech', '452 384 1201');
insert into customer (id, first_name, last_name, email, job, mobile) values (9, 'Sonny', 'Goschalk', 'sgoschalk8@nba.com', 'Desktop Support Technician', '252 107 0941');
insert into customer (id, first_name, last_name, email, job, mobile) values (10, 'Mohammed', 'Raccio', 'mraccio9@hugedomains.com', 'Structural Engineer', '562 826 9785');
